name: GitHub-Profile-3D-Contrib

on:
  schedule: # Runs daily at 03:00 AM IST (18:30 UTC)
    - cron: "30 18 * * *"
  workflow_dispatch: # Allows manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D GitHub Contribution Calendar

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: sukanyasingh3

      - name: Commit and Push Generated Images
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "Update 3D contribution calendar"; then
            git push
          fi
